
#if defined _smlib_included
	#endinput
#endif
#define _smlib_included

// Workaround for Pawnstudio
#if 0 
	#include <sourcemod>
	#include <sdktools>
#endif

#define SMLIB_VERSION "0.9"

#include <_smlib/general>

#include <_smlib/arrays>
#include <_smlib/clients>
#include <_smlib/debug>
#include <_smlib/dynarrays>
#include <_smlib/edicts>
#include <_smlib/effects>
#include <_smlib/entities>
#include <_smlib/files>
#include <_smlib/game>
#include <_smlib/math>
#include <_smlib/server>
#include <_smlib/strings>
#include <_smlib/sql>
#include <_smlib/teams>
#include <_smlib/vehicles>
#include <_smlib/weapons>
#include <_smlib/world>
